name: Deploy gha-terraform-demo
on:
  workflow_dispatch:
    inputs:
      common_name:
        description: リソースid
        required: true
        type: string 
        default: gha-terraform-demo
      aks_version:
        description: AKSのバージョン
        required: true
        type: string   
        default: 1.26.3
      add_node_pool:
        description: ノードプールを追加する
        required: false
        type: boolean
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_location: Japan East
      TF_VAR_id: ${{ inputs.common_name }}
      TF_VAR_kubernetes_version: ${{ inputs.aks_version }}
      TF_VAR_second_node_pool_enabled: ${{ inputs.add_node_pool }}
    runs-on: ubuntu-latest
 
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Setup Terraform CLI'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6
    - name: 'Terraform init'
      run: terraform init  -backend-config=key=${TF_VAR_id}.tfstate
      working-directory: terraform/main
    - name: 'Terraform plan'
      run: terraform plan -lock=false
      working-directory: terraform/main