# Copyright(C) Nomura Research Institute, Ltd. All Rights Reserved.

name: "400_azure_create_service_health_alert"
on:
    workflow_dispatch:
        inputs:
            ENVIRONMENT:
                description: "環境名"
                type: "string"
                default: "test"
                required: false
jobs:
    job_01:
        name: "950_サービスアラート設定"
        uses: "./.github/workflows/950_create_service_health_alert.yml"
        secrets:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CUSTOMER_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_CUSTOMER_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_CUSTOMER_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_CUSTOMER_TENANT_ID }}
        with:
            ENVIRONMENT: "${{ github.event.inputs.ENVIRONMENT }}"