name: azure subscription rename
on:
    workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs: 
  build-and-deply:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.ARM_CREDENTIAL_JSON}}
          enable-AzPSSession: true
  
      - name: Install Az Subscription
        uses: azure/powershell@v1
        with:
          azPSVersion: "11.3.1"
          inlineScript: |
           Install-Module -Force Az.Subscription

      - name: Rename Subscription
        uses: azure/powershell@v1
        with:
          azPSVersion: "11.3.1"
          inlineScript: |
            Rename-AzSubscription -id 209f9d6d-eb81-457c-912a-8ad751c19d30 -SubscriptionName hogehoge

