name: subscription_deply

on:
    workflow_dispatch:

jobs:
    terraform:
        name: 'Terraform'
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: 'Setup Terraform CLI'
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.2

            - name: 'Terraform init'
              run: terraform init -backend-config=key=subscription.tfstate
              working-directory: terraform/azure/enviroments/develop/subscription

            - name: 'Terraform plan'
              run: terraform plan -lock=false
              working-directory: terraform/azure/enviroments/develop/subscription

#            - name: 'Terraform apply'
#              run: terraform apply -auto-approve -lock=false
#              working-directory: terraform/azure/enviroments/develop/subscription

        