name: azure subscription rename
on:
    workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs: 
  build-and-deply:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.ARM_CREDENTIAL_JSON}}
          enable-AzPSSession: true
  
      - name: Install Az Subscription
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
           Install-Module Az.Subscription

      - name: Install Az Subscription
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            Rename-AzSubscription -id ${{ secrets.ARM_SUBSCRIPTION_ID }} -SubscriptionName hogehoge

