name: 'TerraformCodeCheck'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-code-checker:
    name: Terraform code checker
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4
      # Install the latest version of Terraform CLI
      - uses: hashicorp/setup-terraform@v3

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform fmt
        run: terraform fmt -check -recursive -diff